title: Mubeen Ali Mohammed # your name (or website title) here
logo: "/images/Mubeen pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  5+ years experienced certified Data Analytics professional in the Financial Services Industry seeking the opportunity to empower results with a data-driven approach through the latest analytics toolkit in the Agile way.
  <br><br>
  Two Master's degree holder in Data Analytics and Actuarial Science. 1:1 Bachelor’s degree in Electronics Engineering fostered data driven problem solving skills.
  <br><br>
 # <a href="https://www.linkedin.com/in/mubiinali/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-9T4M2C8M2P # your Google Analytics tracking ID here

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-9T4M2C8M2P"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-9T4M2C8M2P');
</script>

colors:
  crimson: '#900C3F'
